//! Caller-driven, disclosure-bounded status and attestation resources.
//!
//! The helper constructs resource metadata and read results but does not
//! register resources, enable server capabilities, or authorize requests.
//! Applications remain responsible for authentication, authorization, and
//! deciding whether to expose the returned URIs.

use std::time::{SystemTime, UNIX_EPOCH};

use mcp_toolkit_provenance::{AttestationEnvelope, AttestationStatus, ATTESTATION_SCHEMA_VERSION};
use rmcp::model::{
    CacheScope, ListResourcesResult, ProtocolVersion, ReadResourceResult, Resource,
    ResourceContents, ResultType,
};
use serde_json::Value;

const CURRENT_PROTOCOL: ProtocolVersion = ProtocolVersion::V_2026_07_28;

/// Describes a closed operational state without free-form host details.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OperationalState {
    Ready,
    Degraded,
    Unavailable,
}

/// Supplies the bounded values shown by the status resource.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OperationalStatus {
    pub state: OperationalState,
    pub component: String,
    pub server_version: String,
}

/// Validated caller-selected URIs for the two optional resources.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OperationalResourceUris {
    status: String,
    attestation: String,
}

/// Describes a bounded construction or projection failure.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OperationalResourceError {
    InvalidUri,
    DuplicateUris,
    InvalidInput,
    UnknownResource,
}

impl std::fmt::Display for OperationalResourceError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let message = match self {
            Self::InvalidUri => "invalid operational resource URI",
            Self::DuplicateUris => "operational resource URIs must be distinct",
            Self::InvalidInput => "invalid operational resource input",
            Self::UnknownResource => "unknown operational resource URI",
        };
        formatter.write_str(message)
    }
}

impl std::error::Error for OperationalResourceError {}

impl OperationalResourceUris {
    /// Validates two distinct caller-namespaced custom-scheme resource URIs.
    ///
    /// # Errors
    /// Returns a bounded error when either URI is malformed, uses a standard
    /// network or file scheme, or duplicates the other URI.
    ///
    /// # Security
    /// URI validation prevents malformed or network/file URIs from being
    /// mistaken for caller-selected custom resource identifiers. It does not
    /// authorize access to a registered resource.
    pub fn new(
        status: impl Into<String>,
        attestation: impl Into<String>,
    ) -> Result<Self, OperationalResourceError> {
        let status = status.into();
        let attestation = attestation.into();
        if !is_custom_resource_uri(&status) || !is_custom_resource_uri(&attestation) {
            return Err(OperationalResourceError::InvalidUri);
        }
        if status == attestation {
            return Err(OperationalResourceError::DuplicateUris);
        }
        Ok(Self {
            status,
            attestation,
        })
    }

    /// Returns standard MCP resource definitions for caller registration.
    pub fn resources(&self) -> Vec<Resource> {
        vec![
            Resource::new(self.status.clone(), "Operational status")
                .with_description("Closed operational state and component version")
                .with_mime_type("application/json"),
            Resource::new(self.attestation.clone(), "Runtime attestation")
                .with_description("Disclosure-bounded runtime attestation")
                .with_mime_type("application/json"),
        ]
    }

    /// Builds the list result with cache hints for the negotiated protocol.
    pub fn list_result(&self, version: &ProtocolVersion) -> ListResourcesResult {
        let mut result = ListResourcesResult::with_all_items(self.resources());
        apply_list_protocol_fields(&mut result, version);
        result
    }

    /// Builds a status read result using a timestamp generated by this helper.
    ///
    /// # Errors
    /// Returns a generic error when the component or version is not a bounded
    /// ASCII identifier suitable for this projection.
    ///
    /// # Security
    /// The helper emits only the closed state, validated identifiers, and its
    /// own timestamp; callers must authorize reads before invoking it.
    pub fn read_status(
        &self,
        uri: &str,
        status: &OperationalStatus,
        version: &ProtocolVersion,
    ) -> Result<ReadResourceResult, OperationalResourceError> {
        if uri != self.status {
            return Err(OperationalResourceError::UnknownResource);
        }
        validate_component_version(&status.component, &status.server_version)?;
        let timestamp_unix_ms = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map_or(0, |duration| {
                duration.as_millis().min(u128::from(u64::MAX)) as u64
            });
        let payload = serde_json::json!({
            "schema_version": ATTESTATION_SCHEMA_VERSION,
            "status": operational_state_name(status.state),
            "component": status.component,
            "server_version": status.server_version,
            "timestamp": timestamp_unix_ms,
        });
        Ok(resource_read_result(uri, payload, version))
    }

    /// Builds an allowlisted attestation result from the typed provenance value.
    ///
    /// # Errors
    /// Returns a generic error when the input schema version is not v2 or the
    /// projected component/version values fail bounded validation.
    ///
    /// # Security
    /// The projection intentionally omits identity overrides, source metadata,
    /// runtime paths and IDs, and free-form unavailable reasons. Callers must
    /// authorize reads before invoking it.
    pub fn read_attestation(
        &self,
        uri: &str,
        envelope: &AttestationEnvelope,
        version: &ProtocolVersion,
    ) -> Result<ReadResourceResult, OperationalResourceError> {
        if uri != self.attestation {
            return Err(OperationalResourceError::UnknownResource);
        }
        if envelope.schema_version != ATTESTATION_SCHEMA_VERSION {
            return Err(OperationalResourceError::InvalidInput);
        }
        let server_version = &envelope.attestation.identity.server_version;
        validate_component_version(&envelope.component, server_version)?;
        let payload = serde_json::json!({
            "schema_version": ATTESTATION_SCHEMA_VERSION,
            "status": status_name(&envelope.status),
            "component": envelope.component,
            "server_version": server_version,
            "unavailable": safe_unavailable_pairs(envelope),
        });
        Ok(resource_read_result(uri, payload, version))
    }
}

fn resource_read_result(
    uri: &str,
    payload: Value,
    version: &ProtocolVersion,
) -> ReadResourceResult {
    let mut result =
        ReadResourceResult::new(vec![
            ResourceContents::text(payload.to_string(), uri).with_mime_type("application/json")
        ]);
    apply_read_protocol_fields(&mut result, version);
    result
}

fn apply_list_protocol_fields(result: &mut ListResourcesResult, version: &ProtocolVersion) {
    if version >= &CURRENT_PROTOCOL {
        result.result_type = Some(ResultType::COMPLETE);
        result.ttl_ms = Some(0);
        result.cache_scope = Some(CacheScope::Private);
    } else {
        result.result_type = None;
        result.ttl_ms = None;
        result.cache_scope = None;
    }
}

fn apply_read_protocol_fields(result: &mut ReadResourceResult, version: &ProtocolVersion) {
    if version >= &CURRENT_PROTOCOL {
        result.result_type = Some(ResultType::COMPLETE);
        result.ttl_ms = Some(0);
        result.cache_scope = Some(CacheScope::Private);
    } else {
        result.result_type = None;
        result.ttl_ms = None;
        result.cache_scope = None;
    }
}

fn is_custom_resource_uri(uri: &str) -> bool {
    if !uri.is_ascii()
        || uri.chars().any(char::is_whitespace)
        || uri.bytes().any(|byte| byte < 0x20 || byte == 0x7f)
    {
        return false;
    }
    let Some((scheme, authority_and_path)) = uri.split_once("://") else {
        return false;
    };
    let mut chars = scheme.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !first.is_ascii_alphabetic()
        || !chars.all(|ch| ch.is_ascii_alphanumeric() || matches!(ch, '+' | '.' | '-'))
        || matches!(
            scheme.to_ascii_lowercase().as_str(),
            "http" | "https" | "file" | "ftp"
        )
    {
        return false;
    }
    let authority = authority_and_path.split('/').next().unwrap_or_default();
    !authority.is_empty() && !uri.chars().any(|ch| matches!(ch, '?' | '#'))
}

fn validate_component_version(
    component: &str,
    version: &str,
) -> Result<(), OperationalResourceError> {
    fn valid(value: &str) -> bool {
        !value.is_empty()
            && value.len() <= 64
            && value
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'_' | b'-'))
    }
    if valid(component) && valid(version) {
        Ok(())
    } else {
        Err(OperationalResourceError::InvalidInput)
    }
}

fn status_name(status: &AttestationStatus) -> &'static str {
    match status {
        AttestationStatus::Ok => "ok",
        AttestationStatus::Degraded => "degraded",
        AttestationStatus::Error => "error",
    }
}

fn operational_state_name(status: OperationalState) -> &'static str {
    match status {
        OperationalState::Ready => "ready",
        OperationalState::Degraded => "degraded",
        OperationalState::Unavailable => "unavailable",
    }
}

fn safe_unavailable_pairs(envelope: &AttestationEnvelope) -> Vec<Value> {
    envelope
        .unavailable
        .iter()
        .filter_map(|unavailable| {
            let pair = match (unavailable.field.as_str(), unavailable.code.as_str()) {
                ("attestation.component", "provenance.unavailable.required") => {
                    ("component", "required")
                }
                ("attestation.identity.server_version", "provenance.unavailable.required") => {
                    ("server_version", "required")
                }
                ("attestation.identity.build_identity", "provenance.unavailable.required") => {
                    ("build_identity", "required")
                }
                ("attestation.identity.source_fingerprint", "provenance.unavailable.required") => {
                    ("source_fingerprint", "required")
                }
                ("attestation.source.revision", "provenance.unavailable.git_revision") => {
                    ("source_revision", "revision")
                }
                ("attestation.source.dirty", "provenance.unavailable.dirty_state") => {
                    ("source_dirty", "dirty_state")
                }
                ("attestation.source.reference", "provenance.unavailable.git_reference") => {
                    ("source_reference", "reference")
                }
                (
                    "attestation.build_metadata.rustc_version",
                    "provenance.unavailable.rustc_version",
                ) => ("compiler_version", "compiler"),
                ("attestation.runtime.pid", "provenance.unavailable.process_id") => {
                    ("process_id", "process")
                }
                (
                    "attestation.runtime.executable_path",
                    "provenance.unavailable.executable_path",
                ) => ("executable", "runtime"),
                ("attestation.runtime.binary_size_bytes", "provenance.unavailable.binary_size") => {
                    ("binary_size", "runtime")
                }
                (
                    "attestation.runtime.binary_modified_unix_ms",
                    "provenance.unavailable.binary_mtime",
                ) => ("binary_mtime", "runtime"),
                _ => return None,
            };
            Some(serde_json::json!({"field": pair.0, "code": pair.1}))
        })
        .take(16)
        .collect()
}
